name: Add review checklist
on:
  pull_request_target:
    types: [opened]
    branches: [main]
permissions:
  pull-requests: write
jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Token available: ${{ secrets.GITHUB_TOKEN != '' }}"
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add review checklist
        uses: trixi-framework/add-pr-review-checklist@v1
        with:
          file: '.github/PULL_REQUEST_TEMPLATE/pull_request_template.md'
